### general ###
server:
  port: 8090


### security ###
authentication:
  type:
    cookie:
      enabled: true
    jwt:
      enabled: false
  provider:
    memory:
      enabled: true
    custom-dao:
      enabled: false


### actuator ###
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,mappings,env # TODO: secure or remove env, mappings

info.app.name: Diet Tracker Backend
info.app.description: REST API for Diet Tracker App
info.app.version: 0.1