### general ###
server:
  port: 8090

### database ###
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diet_tracker_demo?useSSL=false
    username: diet_tracker_test
    password:
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true   # workaround for https://hibernate.atlassian.net/browse/HHH-12368
#  spring.jpa.generate-ddl: true
#  spring.jpa.hibernate.ddl-auto: update

### security ###
authentication:
  type:
    cookie.enabled: false
    jwt.enabled: true
  provider:
    memory.enabled: false
    custom-dao.enabled: true
  jwt-secret:

### actuator ###
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,mappings,env # TODO: secure or remove env, mappings
info:
  app:
    name: Diet Tracker Backend
    description: REST API for Diet Tracker App
    version: 0.1